.PHONY: all

all:
	g++ client-shell.cpp -o client-shell
	gcc get-one-file-sig.c -o get-one-file-sig
	gcc get-one-file.c -o get-one-file
	gcc server-slow.c -o server-slow

clean:
	rm -f client-shell get-one-file-sig get-one-file server-slow
